name:                munchman-gloss
version:             0.1.0.0
github:              "githubuser/munchman-gloss"
license:             BSD3
author:              "Roland Stellmach"
maintainer:          "fun.redoc@gmail.com"
copyright:           "2020 Roland"

data-dir: data
data-files:
- level.txt
- BluesLoops_11_StayOnBeat.com.wav
- PacManR1s.png
- PacManR2s.png
- PacManL1s.png
- PacManL2s.png
- PacManU1s.png
- PacManU2s.png
- PacManD1s.png
- PacManD2s.png
- Ghost1.png
- Ghost2.png
- Ghost3.png

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/munchman-gloss#readme>

dependencies:
- base >= 4.7 && < 5
- haskell-dap 
- ghci-dap 
- haskell-debug-adapter
- strict
- directory
- vector
- containers
- lens
- transformers
- monad-loops
- bmp
- gloss
- gloss-juicy
- ALUT
- random
- repa
- hashable
- unordered-containers
- fgl
- JuicyPixels
- GraphTheory

library:
  source-dirs: src
  generated-other-modules:
    - Paths_munchman_gloss

executables:
  munchman-gloss-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - munchman-gloss
    generated-other-modules:
    - Paths_munchman_gloss
      #  munchman-ascii-exe:
      #    main:                Main.hs
      #    source-dirs:         ascii
      #    ghc-options:
      #    - -threaded
      #    - -rtsopts
      #    - -with-rtsopts=-N
      #    dependencies:
      #    - munchman-gloss
      #    generated-other-modules:
      #    - Paths_munchman_gloss

tests:
  munchman-gloss-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - munchman-gloss
